### ISSUE TITLE
buggy with external code editor

### ISSUE THREAD

**Issue by sooonism** [fian46/addons-btree#1]
I just added this and find it buggy with external code editor. I am using `vs code` and the `function` in `task` did not update when i change the function name or add new function. Works well with internal code editor though.

**Comment by fian46** [comment]
After digging Godot documentation unfortunately it is impossible to detect external resource changes with current EditorPlugins API. This bug is remain opened until Godot support such API. i will try to open new issue as a feature request in Godot main repository for this, but until then the internal editor is the way to go.

**Comment by shayneoneill** [comment]
I wonder if, as annoying as it might be, just doing the old "add a space to the end of the file" (or deleting it) after an external edit, in the internal editor, would be enough to trip the behavior.

File system change detections a tricky topic that changes drastically between operating systems. Even ON an operating system (How you do it on Linux for instance depends on what your desktop setup is, etc)

**Comment by fian46** [comment]
fixed in 1.1.8-beta
