### ISSUE TITLE
Visualise the BTree activity while the game is running

### ISSUE THREAD

**Issue by ClubEdNZ** [fian46/addons-btree#15]
I'd like to work on having the btree show the current state of the current node (by colour) for ease of debugging and experimentation. 

Do you have any thoughts on how best to send updates from the running game code (runtime.gd) to the tool graphnodes, in order to update the colors? Apparently add_autoload_singleton() can work, but I've not had any luck.

*Great add-on, by the way. It's working nicely for my project.

**Comment by fian46** [comment]
currently this feature is broken due to bug in Godot engine it self. The EditorInspector class signal is main blocking issue to resolve. I am opening [this bug report](https://github.com/godotengine/godot/issues/41867) in Godot main repository. i am hopping Godot still do maintenance release in near future so i can complete this feature.

**Comment by ClubEdNZ** [comment]
object_id_selected: Emitted when the Edit button of an Object has been pressed in the inspector. 

Silly question, but what's the 'edit' button of an object? 

If related, in init.gd, I'm using: func selection_changed(): if not dock: ...
to keep track of the currently selected node (if it has a BTREE as a child). Oddly that only runs if alter the init.gd script and then save it. But then once I do that, the Tree Editor breaks (even if I only changed a comment line), which is strange.

Does this sound related?

**Comment by fian46** [comment]
Selection changed to handle tree in local tree. Remote tree need editor inspector

**Comment by fian46** [comment]
I am not quite sure what this means. Sorry my english is not so good.

**Comment by fian46** [comment]
If really needed maybe btree can make it own remote tree inspector for current running instance. This can eliminate blockage within godot it self. But required heavy net code to send tree data and current btree state. This is not ideal since godot already sending the same thing. Plus this lib written in gdscript, debugging maybe harder because the heavy net code operation can fill the etire profiler stack and make things worse.

**Comment by fian46** [comment]
i am assuming just by selecting the node in remote inspector can return such id ? i am not aware about EDIT button anywhere so... what do you think ?

![Screenshot from 2020-09-09 17-10-54](https://user-images.githubusercontent.com/13792627/92579442-c66e1580-f2bf-11ea-82ca-7b849a99a594.png)

The debugger idea is get the object id, reverse the id to actual BTREE Node by GDSCRIPT function Object instance_from_id(id), get the runtime_tree then animate the color in editor.

**Comment by fian46** [comment]
closed with #16

**Comment by ClubEdNZ** [comment]
I just learned that on old versions of Godot, the Workspace toolbar had an "edit" button (see the first image, just under the "Script" tab: https://docs.godotengine.org/en/2.1/learning/editor/2d_and_3d_keybindings.html), which is no longer there in the current version. Perhaps object_id_selected() is not supposed to do anything anymore.

**Comment by fian46** [comment]
Too bad i just rewrite custom inspector for it. Its already in my local branch and never pushed.
