### ISSUE TITLE
Realtime editing not working?

### ISSUE THREAD

**Issue by davord45** [fian46/addons-btree#28]
Hi fian46,i was testing version 1.1.5 and i thought you added realtime tree editing.
If you haven't than my mistake for not understanding.But if you have it does not work when i change transition between nodes during runtime.
![image](https://user-images.githubusercontent.com/70846358/93931090-a65a3f80-fd1e-11ea-8812-24f33fb01ef6.png)

Task only prints the parameter 0 and returns success.

**Comment by fian46** [comment]
No this version only do bug fixing. Sometimes when you hot reload script, when game is running but tree is remain intact, the engine is bug and goes to stack underflow. I don't know what is stackunderflow means but i know stackoverflow is and it sounds bad. The tree hot reload is still not implemented.

**Comment by davord45** [comment]
Ah makes sense,i understood you had fixed the bug that prevented tree from being edited in realtime

**Comment by davord45** [comment]
So hot reload will allow tree to be edited in realtime?

**Comment by fian46** [comment]
btree hot reload can allow such thing but i am still figuring out how to do it with current data version is an instance of which btree in running game. The runtime swap facility is there but data versioning is not.

**Comment by davord45** [comment]
So you say Godot engine is lacking the functionality to do realtime editing?

**Comment by fian46** [comment]
It is not godot limitations. it is just my plugins limitations. When i am writing the btree, i am not add specific versioning inside tree data to get identify in runtime by remote debugger. But it is already released so maybe someone already using it. I am not sure how to upgrade current data version to compatible with realtime debug for btree. Maybe i can release new btree with realtime debugging with new version that not compatible with this version ?. Or waiting for godot enhancement plans to create universal id for each node instead of path based. That is completely my fault 😂

**Comment by davord45** [comment]
Well if you mean not compatible as in it will break current BTREE implementation,maybe start like a experimental branch until you make it work with what people already have

**Comment by davord45** [comment]
Like change the data structure but not what is done in the tree editor,if you get me

**Comment by davord45** [comment]
I just saw the video in youtube,will test it right now
