### ISSUE TITLE
Ctrl Z inside of BTREE editor and node function linking

### ISSUE THREAD

**Issue by davord45** [fian46/addons-btree#31]
Hi fian46.
I was wondering if you can make undo work inside of the editor,cause now it kind of returns you to the last edited tree and if its not a hassle could you maybe link the node with a script when pressed (with CTRL+some combination) to send you to the scripting tab and shows you the function that its using? That would be a nice quality of life feature,would save much time.

**Comment by fian46** [comment]
not sure undo redo can be implemented fully due to bug in godot graphedit class that not recognize start_node_moving and end_node_moving signal. i will rather not implement it instead of half implementation. but the functionality is there ready when godot fixed it it can be activated.
for jump to source code it fixed in branch "jump_to_sourcecode", it still need more testing for sure but i think it stable enough.

**Comment by davord45** [comment]
Such a nice improvement,works great.On the godot bug,have you made an issue on the godot github?

**Comment by fian46** [comment]
I am not yet submit a bug report. Maybe in the future 😜
