### ISSUE TITLE
GOAP integration

### ISSUE THREAD

**Issue by davord45** [fian46/addons-btree#36]
Hi fian46.
I was wondering,could there be a way to integrate Goal Oriented Action Planning into this addon.
I know there is one made for Godot but it does not have ease of use like this addon does. If you dont want to integrated with this,could you base a different addon that uses GOAP?It would be a killer AI combination.

Just asking,big fan of this addon and what you have done.

**Comment by davord45** [comment]
I found that FSMs can be done with Behavior Tree,but GOAP is a way more dynamic way of AI behavior,so mixing BTREE planning with GOAP would be awesome.

**Comment by fian46** [comment]
You mean we should add GOAP specific node ?

**Comment by davord45** [comment]
Well GOAP AI works in a way that it analyses its environment and reacts accordingly with set of actions that is given to it.It makes it more dynamic.

https://youtu.be/PaOLBOuyswI?t=69
This video explains how it works in a game like F.E.A.R

So maybe we can add a way for BTREE to act in a similar way.Let me know if you think this is possible?

**Comment by davord45** [comment]
Although your addon is very versatile when it comes to customizability.Switching between actions based on priority and cost,like it does in GOAP is missing i think.

**Comment by davord45** [comment]
https://www.slideshare.net/AakashChotrani/what-is-goap-and-why-is-it-not-already-mainstream
According to this paper,GOAP Agent creates a BTREE according to the state that he is in.

**Comment by fian46** [comment]
Yes you're right the addon is half of the solution for GOAP. BT can be ticked manually so it can be the action side but it need complex action planning to generate optimal ai solution like GOAP.

**Comment by davord45** [comment]
In the video i send,he says that it uses A* algorithm

**Comment by davord45** [comment]
https://github.com/crashkonijn/GOAP
There is a Unity open source addon for GOAP that shows it visually.Maybe it helps to give you ideas.

**Comment by fian46** [comment]
So the action planning is a a* for given goal. 

> In the video i send,he says that it uses A* algorithm,and that algorithm is cost driven.

Interesting maybe with some more research i can make it a custom node fo it.

**Comment by fian46** [comment]
Well after do some research about goap and bt i figured that you can't mixing both and i really surprised myself. You only can choose one. Integrate goat in this plugins can cause a difficult. Goap sounds awesome but in implementations it can cause hard to debug ai because some times the created graph ended no where you want due to incomplete action chain (well in plugins it can detect this problem but still it difficult to debug until it behave really wrong). Bt in other hand required a lot of thing but the debugging is clear because the rule is clear. It is not really hard to write nice goap plugins but i don't think i need it at the moment.

**Comment by davord45** [comment]
Understandable,i thought it would be difficult.Was just wondering if it was possible to mix them up.But since you brought those points it makes sense not to.Anyway thanks for taking the time to research
